//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandsiteMobile.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LandsiteMobile.Resources.Languages.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        internal static string accountEditProfile {
            get {
                return ResourceManager.GetString("accountEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string accountLogout {
            get {
                return ResourceManager.GetString("accountLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damages.
        /// </summary>
        internal static string homeDamages {
            get {
                return ResourceManager.GetString("homeDamages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate the damages.
        /// </summary>
        internal static string homeDamagesPlaceholder {
            get {
                return ResourceManager.GetString("homeDamagesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position along the hill.
        /// </summary>
        internal static string homeHill {
            get {
                return ResourceManager.GetString("homeHill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the position of the landslide.
        /// </summary>
        internal static string homeHillPlaceholder {
            get {
                return ResourceManager.GetString("homeHillPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Landslide.
        /// </summary>
        internal static string homeInfoLandslide {
            get {
                return ResourceManager.GetString("homeInfoLandslide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of landslide *.
        /// </summary>
        internal static string homeLandslide {
            get {
                return ResourceManager.GetString("homeLandslide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the type of the landslide.
        /// </summary>
        internal static string homeLandslidePlaceholder {
            get {
                return ResourceManager.GetString("homeLandslidePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of material.
        /// </summary>
        internal static string homeMaterial {
            get {
                return ResourceManager.GetString("homeMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the type of the material.
        /// </summary>
        internal static string homeMaterialPlaceholder {
            get {
                return ResourceManager.GetString("homeMaterialPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitigation measures.
        /// </summary>
        internal static string homeMeasures {
            get {
                return ResourceManager.GetString("homeMeasures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate the mitigation measures.
        /// </summary>
        internal static string homeMeasuresPlaceholder {
            get {
                return ResourceManager.GetString("homeMeasuresPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Landslide.
        /// </summary>
        internal static string homeNewLandside {
            get {
                return ResourceManager.GetString("homeNewLandside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional notes.
        /// </summary>
        internal static string homeNote {
            get {
                return ResourceManager.GetString("homeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add additional notes.
        /// </summary>
        internal static string homeNotePlaceholder {
            get {
                return ResourceManager.GetString("homeNotePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo *.
        /// </summary>
        internal static string homePhoto {
            get {
                return ResourceManager.GetString("homePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Landslide.
        /// </summary>
        internal static string homePosition {
            get {
                return ResourceManager.GetString("homePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Indicates a required field.
        /// </summary>
        internal static string homeRequired {
            get {
                return ResourceManager.GetString("homeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring systems.
        /// </summary>
        internal static string homeSystem {
            get {
                return ResourceManager.GetString("homeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate the monitoring systems.
        /// </summary>
        internal static string homeSystemPlaceholder {
            get {
                return ResourceManager.GetString("homeSystemPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence of vegetation.
        /// </summary>
        internal static string homeVegetation {
            get {
                return ResourceManager.GetString("homeVegetation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate the presence of vegetation.
        /// </summary>
        internal static string homeVegetationPlaceholder {
            get {
                return ResourceManager.GetString("homeVegetationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence of water.
        /// </summary>
        internal static string homeWater {
            get {
                return ResourceManager.GetString("homeWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate the presence of water.
        /// </summary>
        internal static string homeWaterPlaceholder {
            get {
                return ResourceManager.GetString("homeWaterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a mitigation measure.
        /// </summary>
        internal static string landslideMeasureAdd {
            get {
                return ResourceManager.GetString("landslideMeasureAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the mitigation measure(s).
        /// </summary>
        internal static string landslideMeasureList {
            get {
                return ResourceManager.GetString("landslideMeasureList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there any mitigation measures?.
        /// </summary>
        internal static string landslideMeasureRadio {
            get {
                return ResourceManager.GetString("landslideMeasureRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a monitoring system.
        /// </summary>
        internal static string landslideSystemAdd {
            get {
                return ResourceManager.GetString("landslideSystemAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the monitoring system(s).
        /// </summary>
        internal static string landslideSystemList {
            get {
                return ResourceManager.GetString("landslideSystemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there any monitoring system?.
        /// </summary>
        internal static string landslideSystemRadio {
            get {
                return ResourceManager.GetString("landslideSystemRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string loginButtonLogin {
            get {
                return ResourceManager.GetString("loginButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string loginDontHaveAccount {
            get {
                return ResourceManager.GetString("loginDontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        internal static string loginEmailPlacehold {
            get {
                return ResourceManager.GetString("loginEmailPlacehold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        internal static string loginErrorEmail {
            get {
                return ResourceManager.GetString("loginErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string loginErrorPassword {
            get {
                return ResourceManager.GetString("loginErrorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string loginForgotPassword {
            get {
                return ResourceManager.GetString("loginForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string loginPasswordPlacehold {
            get {
                return ResourceManager.GetString("loginPasswordPlacehold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        internal static string loginSignup {
            get {
                return ResourceManager.GetString("loginSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string settingAccount {
            get {
                return ResourceManager.GetString("settingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        internal static string settingExpert {
            get {
                return ResourceManager.GetString("settingExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string settingLanguage {
            get {
                return ResourceManager.GetString("settingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settingTitle {
            get {
                return ResourceManager.GetString("settingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string signupAccept {
            get {
                return ResourceManager.GetString("signupAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string signupAge {
            get {
                return ResourceManager.GetString("signupAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string signupButton {
            get {
                return ResourceManager.GetString("signupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children&apos;s Information.
        /// </summary>
        internal static string signupChildrenInformation {
            get {
                return ResourceManager.GetString("signupChildrenInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.
        ///
        ///LandslidesSurvey does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such infor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string signupChildrenInformationDes {
            get {
                return ResourceManager.GetString("signupChildrenInformationDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password *.
        /// </summary>
        internal static string signupConfirm {
            get {
                return ResourceManager.GetString("signupConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent.
        /// </summary>
        internal static string signupConsent {
            get {
                return ResourceManager.GetString("signupConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By using our website, you hereby consent to our Privacy Policy and agree to its terms..
        /// </summary>
        internal static string signupConsentDes {
            get {
                return ResourceManager.GetString("signupConsentDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        internal static string signupDisclaimer {
            get {
                return ResourceManager.GetString("signupDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address *.
        /// </summary>
        internal static string signupEmail {
            get {
                return ResourceManager.GetString("signupEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Data Protection Regulation (GDPR).
        /// </summary>
        internal static string signupGDPR {
            get {
                return ResourceManager.GetString("signupGDPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are a Data Controller of your information.
        ///LandslidesSurvey legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Information we collect and the specific context in which we collect the information:
        ///          - LandslidesSurvey needs to perform a contract with you
        ///          - You have given LandslidesSurvey permission to do so
        ///          - Processing your personal information is in LandslidesSurvey legitimate interests
        ///          - Lands [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string signupGDPRDes {
            get {
                return ResourceManager.GetString("signupGDPRDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string signupGender {
            get {
                return ResourceManager.GetString("signupGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string signupGoBack {
            get {
                return ResourceManager.GetString("signupGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string signupHaveAccount {
            get {
                return ResourceManager.GetString("signupHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Files.
        /// </summary>
        internal static string signupLogFiles {
            get {
                return ResourceManager.GetString("signupLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LandslidesSurvey follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services&apos; analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string signupLogFilesDes {
            get {
                return ResourceManager.GetString("signupLogFilesDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string signupLogin {
            get {
                return ResourceManager.GetString("signupLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        internal static string signupOccupation {
            get {
                return ResourceManager.GetString("signupOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Privacy Policy Only.
        /// </summary>
        internal static string signupOnlinePrivacyPolicyOnly {
            get {
                return ResourceManager.GetString("signupOnlinePrivacyPolicyOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in LandslidesSurvey. This policy is not applicable to any information collected offline or via channels other than this website..
        /// </summary>
        internal static string signupOnlinePrivacyPolicyOnlyDes {
            get {
                return ResourceManager.GetString("signupOnlinePrivacyPolicyOnlyDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password *.
        /// </summary>
        internal static string signupPassword {
            get {
                return ResourceManager.GetString("signupPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policies.
        /// </summary>
        internal static string signupPrivacyPolicies {
            get {
                return ResourceManager.GetString("signupPrivacyPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on LandslidesSurvey, which are sent directly to users&apos; browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit.
        ///
        ///Note that LandslidesSurvey has no access  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string signupPrivacyPoliciesDes {
            get {
                return ResourceManager.GetString("signupPrivacyPoliciesDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy for LandslidesSurvey.
        /// </summary>
        internal static string signupPrivacyPolicyForLandslidesSurvey {
            get {
                return ResourceManager.GetString("signupPrivacyPolicyForLandslidesSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At LandslidesSurvey, accessible from https://github.com/epessina/LandslidesSurvey, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by LandslidesSurvey and how we use it.\nIf you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us..
        /// </summary>
        internal static string signupPrivacyPolicyForLandslidesSurveyDes {
            get {
                return ResourceManager.GetString("signupPrivacyPolicyForLandslidesSurveyDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Indicateds a required field.
        /// </summary>
        internal static string signupRequired {
            get {
                return ResourceManager.GetString("signupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Party Privacy Policies.
        /// </summary>
        internal static string signupThirdPartyPrivacyPolicies {
            get {
                return ResourceManager.GetString("signupThirdPartyPrivacyPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LandslidesSurvey&apos;s Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options. You may find a complete list of these Privacy Policies and their links here: Privacy Policy Links.
        ///
        ///You can choose to disable cookies through your individual browser options. To know more detailed informati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string signupThirdPartyPrivacyPoliciesDes {
            get {
                return ResourceManager.GetString("signupThirdPartyPrivacyPoliciesDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Sign up -.
        /// </summary>
        internal static string signupTitle {
            get {
                return ResourceManager.GetString("signupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellcome.
        /// </summary>
        internal static string Wellcome {
            get {
                return ResourceManager.GetString("Wellcome", resourceCulture);
            }
        }
    }
}
